# Lint, test and deploy application.
# Required environment variables:
# - ENV: the environment being targeted (qa, prod)
# - COGNITO_USER_POOL_ARN: the ARN of the cognito user pool to be used for authorization
version: 0.2
phases:
  install:
    commands:
      - ls -al
      - cp ${CODEBUILD_SRC_DIR}/config.template.yml ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_ENV;${BUILD_ENV};g"                                       ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_APP_NAME;${BUILD_APP_NAME};g"                             ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_LAMBDA_ROLE_ARN;${BUILD_LAMBDA_ROLE_ARN};g"               ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_API_ID;${BUILD_API_ID};g"                                 ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_SSM_PREFIX;${BUILD_SSM_PREFIX};g"                         ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_API_ROOT_ID;${BUILD_API_ROOT_ID};g"                       ${CODEBUILD_SRC_DIR}/config.yml
      - sed -i "s;BUILD_COGNITO_POOL_ARN;${BUILD_COGNITO_POOL_ARN};g"             ${CODEBUILD_SRC_DIR}/config.yml
      - cat ${CODEBUILD_SRC_DIR}/config.yml
      - echo Installing serverless...
      - npm install -g serverless@3.32.2
      - echo Installing source NPM dependencies...
      - pwd
      - npm install
  build:
    commands:
      - serverless deploy
artifacts:
  discard-paths: yes
  files:
    – serverless.yml
